spring:
  profiles:
    active: nonprod
---
spring:
  profiles: dev
  data.mongodb:
    host: localhost
    port: 27017
    database: local
server:
  port: 8282
---
spring:
  profiles: nonprod
  data.mongodb:
    host: localhost
    port: 27017
    database: local
server:
  port: 8283
---
spring:
  profiles: prod
  data.mongodb:
    host: localhost
    port: 27017
    database: local
server:
  port: 8284